gcp:
  project_id: error-fixer-23274
  region: us-central1
  service_name: error-screen-fix-backend

runtime: python311

env_variables:
  FLASK_ENV: production
  PORT: 8080
  SECRET_KEY: your-production-secret-key
  JWT_SECRET_KEY: your-production-jwt-secret
  DATABASE_URL: sqlite:///instance/app.db

automatic_scaling:
  min_instances: 0
  max_instances: 10

